### ISSUE TITLE
Changing the cron line

### ISSUE THREAD

**Issue by haydonryan** [helphi/Dockerfile-apt-mirror#1]
Hi there,
Thank you for putting this repository out there. I tried to implement this on my Synology NAS using docker but ran into a few problems.   

Debugging the issue became problematic (corn job didn't run but didn't return any errors).  
I'd suggest changing this line to append the file (you'll need to touch it first though) and also redirect stderr to stdout. 
`echo "0 3 * * * root /usr/bin/apt-mirror > /var/spool/apt-mirror/cron.log" > cron.d/apt-mirror`

I ended up with a line like:
`echo -e "0 3 * * * /usr/bin/apt-mirror >> /var/spool/apt-mirror/cron.log 2>&1\n" > apt-mirror`

This brought up my next error - when the task ran - I got the error `/bin/sh: 1: root: not found`

Which means (at least for my scenario) I need to remove the user. I haven't tried it on any other docker hosts.

Were you able to run this without editing files in the container?

I didn't want to submit a PR in case this worked on your setup. 

Also I think I needed to run crontab on the file to get it to register the corn job.

Thanks again!

**Comment by helphi** [comment]
I can run it with `docker 19.03.8` on `Ubuntu 20.04` now, and i had test it about 3 years ago with an older docker version.

```bash
root@x:/home/x# mkdir cron.d
root@x:/home/x# echo "53 0 * * * root /usr/bin/apt-mirror > /var/spool/apt-mirror/cron.log" > cron.d/apt-mirror
root@x:/home/x# chown root:root cron.d/apt-mirror
root@x:/home/x# chmod 644 cron.d/apt-mirror
root@x:/home/x# docker run   -v $PWD/apt-mirror:/var/spool/apt-mirror   -v $PWD/cron.d:/etc/cron.d   helphi/apt-mirror:xenial
```

```bash
x@x:~$ ls apt-mirror/
cron.log  mirror  skel  var
x@x:~$ cat apt-mirror/cron.log 
Downloading 162 index files using 20 threads...
Begin time: Fri Jul 17 00:53:01 2020
[20]... [19]... [18]... [17]... [16]... [15]... [14]... [13]... [12]... [11]... [10]... [9]... [8]... [7]... [6]... [5]... 
```

I found that you did not use `root` user to run the `apt-mirror` command, maybe Synology NAS  don't allow `root` user to run the `cron -f` command. So you may need to change the Dockerfile to let a regular user to run `cron -f`, and then build your own docker image.

**Comment by haydonryan** [comment]
Oh awesome :) 

Looks like the apt-mirror code itself has some major flaws too which is a bit disappointing, but understandable if things act differently.
